# Generated by Django 2.0.1 on 2018-01-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('question', models.TextField(help_text='Markdown Field')),
                ('hint', models.TextField(help_text='Markdown Field')),
                ('question_type', models.IntegerField(choices=[(0, 'Short Answer'), (1, 'Multiple Choice'), (2, 'Regular Expression')], default=0)),
                ('short_answer', models.CharField(help_text="Use for 'Short Answer' and 'Multiple Choice' questions.", max_length=128)),
                ('multiple_choice_options', models.TextField(help_text='Put one choice per line.')),
                ('regex_answer', models.CharField(help_text="Regular expression to test answer against for 'Regular Expression' questions.", max_length=128)),
                ('points', models.IntegerField(default=10)),
                ('hint_cost', models.IntegerField(default=2)),
                ('wrong_answer_cost', models.IntegerField(default=1)),
                ('data_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
