# Generated by Django 2.0.1 on 2018-01-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='multiple_choice_options',
            field=models.TextField(blank=True, default='Option 1\nOption 2\nOption3\nOption4', help_text='Put one choice per line.'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='regex_answer',
            field=models.CharField(blank=True, help_text="Regular expression to test answer against for 'Regular Expression' questions.", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='short_answer',
            field=models.CharField(blank=True, help_text="Use for 'Short Answer' and 'Multiple Choice' questions.", max_length=128, null=True),
        ),
    ]
