# Generated by Django 2.0.1 on 2018-01-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparticipationrecord',
            name='hints_purchased',
            field=models.ManyToManyField(blank=True, related_name='hint_purchasers', to='main.Challenge'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='multiple_choice_options',
            field=models.TextField(blank=True, default='Option 1\nOption 2\nOption3\nOption4', help_text='Put one choice per line.', null=True),
        ),
        migrations.AlterField(
            model_name='userparticipationrecord',
            name='challenges_solved',
            field=models.ManyToManyField(blank=True, to='main.Challenge'),
        ),
    ]
