# Generated by Django 2.0.1 on 2018-01-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180117_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Experimental'), (2, 'Published')], default=0),
        ),
    ]
