# Generated by Django 2.0.1 on 2018-01-19 18:18

from django.db import migrations
import jfmario_django.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180119_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparticipationrecord',
            name='wrong_answers',
            field=jfmario_django.model_fields.JsonField(blank=True, null=True),
        ),
    ]
