# Generated by Django 2.0.1 on 2018-01-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_challenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='regex_input_type',
            field=models.IntegerField(choices=[(0, 'Text'), (1, 'Textarea')], default=0, help_text="How should users input their answers for 'Regular Expression' questions?"),
        ),
    ]
